# Site settings
title: PengGuo.xyz
email: guoleii@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Focus on Apple TV app development.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://PengGuo.xyz" # the base hostname & protocol for your site
twitter_username: NilStack
github_username:  NilStack

# Build settings
markdown: kramdown
