# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            NilStack
tagline:          ''
description:      ''
url:              http://nilstack.github.io
baseurl:          '/'
paginate:         3

author:
  name:           'Peng Guo'
  url:            https://twitter.com/nilstack

# Custom vars
version:          0.0.1
