# Site settings
title: PengGuo.xyz
email: guoleii@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  macOS. iOS. watchOS. tvOS.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://pengguo.xyz" # the base hostname & protocol for your site
twitter_username: NilStack
github_username:  NilStack

# Build settings
markdown: kramdown
